= Requirements Handbook Companion
//------------------------- configuration
:imagesdir: images
:icons: font
:toc:
:numbered:

:method: pass:[<b>PEGS</b>]
:hb-pdf: http://se.ethz.ch/~meyer/down/requirements_handbook/REQUIREMENTS.pdf
:hb-title: Handbook of requirements and business analysis
:hb-url: http://requirements-handbook.org/
:cb-url: https://docs.google.com/document/d/1HrWCRzyW_iTf1QXFFzEoDvvc66IzMCDb3uXGS5GRWz8/edit?usp=sharing
:github-repo: https://github.com/FormalRequirements/requirements-handbook
:github-io: https://FormalRequirements.github.io/requirements-handbook

// icons for GitHub
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
//-------------------------------------

ifndef::pdf-backend[]
//------------------------------------ Badges --------
image:https://github.com/FormalRequirements/requirements-handbook/workflows/Check%20Markdown%20links/badge.svg[Check Markdown links,link="https://github.com/FormalRequirements/requirements-handbook/actions"]
image:https://img.shields.io/badge/License-MIT-yellow.svg[License: MIT, link="https://opensource.org/licenses/MIT"]
image:https://img.shields.io/badge/Gitpod-ready--to--code-blue?logo=gitpod[Gitpod ready-to-code ,link="https://gitpod.io/#https://github.com/FormalRequirements/requirements-handbook"]
image:https://img.shields.io/badge/PDF-Download-blue[PDF download,link="https://github.com/FormalRequirements/requirements-handbook/blob/main/README.pdf"]

//------------------------------------ Badges --------
endif::[]

:numbered:
== Disclaimer

WARNING: Work in progress!

Here is a list of warnings:

- This work is in progress and subject to constant improvements, so pay attention to dates and versions. 
- If you read the `PDF` version of this material on a browser, the links might not be clickable. 
Download it instead in your machine and open it with a PDF viewer. 
The links should be clickable there.

:numbered:
//-------------------------------------
== Context

This repository constitutes the companion of the book: link:{hb-pdf}[{hb-title}].
It serves as the basis for the future Handbook's site: {hb-url}

ifdef::env-github[]
//-------------------------------------
== Overview of the method 

See the dedicated file: link:overview.adoc[]
endif::[]

ifndef::env-github[]
include::overview.adoc[leveloffset=+1]
endif::[]


== Case studies

We illustrate the use of {method} through the following case studies:

WARNING: Work in progress

. The Roborace
. A more information-system-oriented example
. This Companion Book 


== Book templates

We provide a set of Book templates in this companion web site to help you apply {method} and organize your requirements.
Here is the list of the available templates (feel free to link:CONTRIBUTING.adoc[contribute] by submitting additional templates):

WARNING: Work in progress

. DOCX
. Google Doc (see {cb-url}[this example] for now)
. LaTeX (see https://laptrinhx.com/a-latex-template-for-a-software-requirements-specification-that-respects-the-ieee-standards-3457260700/[IEEE example])
. link:githubImpl.adoc[GitHub] 

:numbered!:
== Appendices

[appendix]
//-------------------------------------
=== Useful links

- The draft of the Method Book: {hb-pdf}[PDF]
- The draft of the Companion Book: {cb-url}[Google Doc]


[appendix]
//-------------------------------------
=== Specific implementations

Here is a list of potential mappings between the {method}:

SysML:: 
- Each PEGS could be a package
- Requirements could be stereotyped (e.g., `<<Goals>>` or `<<System>>`)

FORM-L::
- M. Thuy could be interested in providing a template for the {method} in Form-L

RSML::
- Florian could integrate the {method} in the editor


ifdef::pdf-backend[]
[appendix]
//-------------------------------------
=== Checks results and issues

==== URLs 

.Checking URLs result (last update: {localdate}):
[source,shell]
--
include::check-results.txt[]
--
endif::[]
ifndef::pdf-backend[]
[appendix]
//-------------------------------------
=== Checks results and issues

==== URLs image:https://github.com/FormalRequirements/requirements-handbook/workflows/Check%20Markdown%20links/badge.svg[Check Markdown links]

Checking URLs result (last update: {localdate}):

See the following file: link:check-results.txt[]
endif::[]