@startuml
'-----------------------------------
' Requirements Method Illustrated
' JMB 2020
'-----------------------------------

' Default settings
'-----------------------------------
!include config.cfg

'title References between PEGS

' Attribute and name values (for translation purpose).
'-----------------------------------

'Bertrand's colors for PEGS
!define GREEN TECHNOLOGY
!define BLUE Blue
!define YELLOW Yellow
!define BLACK Black

together {
class E as "Environment" <<Environment>>
class G as "Goals" <<Goals>> 
}
class P as "Project" <<Project>>
class S as "System" <<System>>

E <.. P
E <. G
P .> S
P ..> G
E <.. S
G <.. S : May reference

@enduml
